Add responsive header
michalzajac123/portfolio pull request #4
Opened 2024-04-22 18:48 UTC by ogonekmateusz

![image](https://github.com/michalzajac123/portfolio/assets/114666895/077d68ec-b9e3-45a3-9b16-96e321912263)
![image](https://github.com/michalzajac123/portfolio/assets/114666895/803075be-9bd0-4e2d-891c-c7e7849904f0)

2024-04-22 18:49 UTC, michalzajac123 commented on src/components/HeaderView.vue
> +            <RouterLink class="nav-link" to="/">Contact</RouterLink>
Dodaj style do contact

2024-04-22 18:50 UTC, ogonekmateusz commented on src/components/HeaderView.vue
> +            <RouterLink class="nav-link" to="/">Contact</RouterLink>
oki

2024-04-22 18:50 UTC, michalzajac123 requested changes
Dodaj style do contact

2024-04-23 07:11 UTC, michalzajac123 approved these changes
Good

2024-04-23 07:15 UTC, merged